apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u0di8pmbz-go 
  janus-idp.io/tekton: u0di8pmbz-go
  backstage.io/kubernetes-id: u0di8pmbz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u0di8pmbz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml