apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u0di8pmbz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u0di8pmbz-go 
  name: u0di8pmbz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u0di8pmbz-go 
